version: '2.4'
services:
  builder:
    image: "rockmyy-builder"
    build:
      context: .
      network: host
    environment:
      CROSS_COMPILE: arm-linux-gnueabi-
    volumes:
    - "./build:/tmp/RockMyy-Build"
    - "./sources:/usr/src"


